### PR TITLE
CI deployment of researcher-reports

### PR DESCRIPTION
**Pull request by sfentress**

### CODE REVIEW

**Comment by sfentress** [comment]
This branch is building correctly and deployed to https://researcher-reports.concord.org/branch/deploy-results-loader/

**Comment by mklewandowski** [comment]
> This branch is building correctly and deployed to https://researcher-reports.concord.org/branch/deploy-results-loader/

I get the "We're sorry, but something went wrong." Portal error when I try to go to that branch.  Is it working for you?

**Comment by mklewandowski** [comment]
Ah, we still had `athena` in the redirect URLs in the auth client.  Should be fixed now.

**Comment by sfentress** [comment]
This is now fixed.

**Review by mklewandowski — APPROVED** [review]
👍 LGTM!

**Pull request merged**
